name: asad_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  qrlink_flux: ^0.0.1
  file_picker: ^10.2.3
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  


flutter:
  uses-material-design: true

  assets: 
    - ./assets/images/image_logo.png
    - ./assets/images/image_login.png
    - ./assets/images/home.png
    - ./assets/images/profil.png
    - ./assets/images/tabungan.png
    - ./assets/images/profile_full.png
    - ./assets/images/home_full.png
    - ./assets/images/tabungan_full.png
    - ./assets/images/vector.png
    - ./assets/images/lokasi.png
    - ./assets/images/pesantren.png
    - ./assets/images/berita1.png
    - ./assets/images/berita2.png
    - ./assets/images/berita3.png
    - ./assets/images/icon_calender.png
    - ./assets/images/qr.png
    - ./assets/images/setor.png
    - ./assets/images/penarikan.png
    - ./assets/images/bukti_berhasil.png
    - ./assets/images/brisetor.png

  fonts:
    - family: Maison Neue
      fonts:
      - asset: ./assets/fonts/Maison Neue.ttf
